#!/usr/bin/env python

import sys
from galton.readout import GaltonBoardRead

#import matplotlib.patches as patches


# import matplotlib as mpl

ro = GaltonBoardRead()

while True:
	print '(q)uit (r)eset (u)pdate'
	inp = raw_input()
	if 'q' in inp:
		sys.exit(0)

	if 'r' in inp:
		ro.reset_counters()
		continue

	if 'u' in inp:
		count = ro.read_from_counters().split()[0]
		count = 'a,%sz' % count
		print count
#		try:
		with open('/var/www/html/galton_counts.txt','w') as f:
				f.write(count + '\n')

