#!/usr/bin/env python

import sys
#from galton.readout import GaltonBoardRead

import matplotlib as mpl
#mpl.rcParams['toolbar'] = 'None'

import matplotlib.patches as patches
import matplotlib.pyplot as plt

fig = plt.figure(figsize=(3.4,6.1))

ax = plt.subplot()

#ax.set_xlim((0,1))
#ax.set_ylim((0,1))

dataplot, = plt.plot([3,5,4,3,2,1,4,6,7,8,1,9,12],'ok')

def key_press(event):
    if event.key == 'q':
        sys.exit(0)
fig.canvas.mpl_connect('key_press_event', key_press)


class ActionDict(dict):
    def __missing__(self, key):
        def do_nothing(): pass
        return do_nothing
action = ActionDict()

button_getdata = patches.Circle((0.25, 0.75), 0.2, picker=1, color='blue', transform=fig.transFigure, clip_on=False)
def getdata():
    print 'get data'
    dataplot.set_data(range(13),[3]*13)
    plt.draw()
action[button_getdata] = getdata
ax.add_patch(button_getdata)


button_reset = patches.Circle((0.75, 0.75), 0.2, picker=1, color='orange', transform=fig.transFigure, clip_on=False)
def reset():
    print 'reset'
    dataplot.set_data(range(13),[0]*13)
    plt.draw()
action[button_reset] = reset
ax.add_patch(button_reset)

fig.canvas.mpl_connect('pick_event', lambda ev: action[ev.artist]() )

textstyle ={
    'color' : 'cyan',
    'fontsize' : 24,
    'transform' : fig.transFigure,
}

plt.text(0.25, 0.75, 'update', **textstyle)
plt.text(0.75, 0.75, 'reset',  **textstyle)

plt.text(0.2,0.02, '%s'%([0]*13), color='k', fontsize=20, transform=fig.transFigure, clip_on=False)

plt.show()

exit(0)


# import matplotlib as mpl

ro = GaltonBoardRead()

while True:
    print '(q)uit (r)eset (u)pdate'
    inp = raw_input()
    if 'q' in inp:
        sys.exit(0)

    if 'r' in inp:
        ro.reset_counters()
        continue

    if 'u' in inp:
        count = ro.read_from_counters().split()[0]
        count = 'a,%sz' % count
        print count
#       try:
        with open('/var/www/html/galton_counts.txt','w') as f:
                f.write(count + '\n')
