/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.0 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Pin_1_aliases.h"
#include "Pin_1.h"
#include "isr_3_sensor.h"
#include "UART_1.h"
#include "sensor_2_aliases.h"
#include "sensor_2.h"
#include "isr_2_sensor.h"
#include "sensor_5_aliases.h"
#include "sensor_5.h"
#include "sensor_1_aliases.h"
#include "sensor_1.h"
#include "isr_5_sensor.h"
#include "sensor_4_aliases.h"
#include "sensor_4.h"
#include "isr_4_sensor.h"
#include "sensor_3_aliases.h"
#include "sensor_3.h"
#include "Pin_2_aliases.h"
#include "Pin_2.h"
#include "serial_in_buff.h"
#include "isr_1_sensor.h"
#include "isr_6_sensor.h"
#include "sensor_6_aliases.h"
#include "sensor_6.h"
#include "isr_7_sensor.h"
#include "sensor_7_aliases.h"
#include "sensor_7.h"
#include "isr_8_sensor.h"
#include "sensor_8_aliases.h"
#include "sensor_8.h"
#include "isr_9_sensor.h"
#include "sensor_9_aliases.h"
#include "sensor_9.h"
#include "isr_10_sensor.h"
#include "sensor_10_aliases.h"
#include "sensor_10.h"
#include "isr_11_sensor.h"
#include "sensor_11_aliases.h"
#include "sensor_11.h"
#include "isr_12_sensor.h"
#include "sensor_12_aliases.h"
#include "sensor_12.h"
#include "isr_13_sensor.h"
#include "sensor_13_aliases.h"
#include "sensor_13.h"
#include "Clock_1.h"
#include "UART_1_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

